#!/bin/bash

set -e

if sudo apt-get update && sudo apt-get full-upgrade; then
    echo "Update/upgrade process complete. Removing unused packages/services..."
    sleep 1
    
    if sudo apt-get autoremove --purge && sudo apt-get clean; then
        sleep 1
        echo "Unusued package and service removal process complete!"
    else
        echo "Oops! Something went wrong during package/service removal." >&2
    fi
    
else
    echo "Oops! Something went wrong during the update/upgrade process." >&2
fi
